version: "3.8"

services:
  app:
    container_name: app-dev
    image: app-dev
    build:
      context: .
      target: development
    environment:
      - PORT
    ports:
      - ${PORT}:3000'
    networks:
      - networks-frontend
    restart: always

networks:
  spelling-dee:
    driver: bridge